name: Build & Pack
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.301"
      - name: Restore Dependencies
        run: dotnet restore src/Daytona.sln
      - name: Build Solution
        run: dotnet build src/Daytona.sln -- configuration Release --no-restore
      - name: Unit Test
        run: dotnet test src/Daytona.Test/Daytona.Test.csproj
