name: Build & Pack
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Package
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore Dependencies
        run: dotnet restore src/Daytona.sln
      - name: Build Solution
        run: dotnet build src/Daytona.sln -- configuration Release --no-restore
      - name: Push Package
        run: |
          dotnet nuget add source --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet pack src/Daytona.sln -c Release
          dotnet nuget push src/Daytona/bin/Release/Daytona.8.0.1.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --source github
