name: Build & Pack
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.301"
      - name: Restore Dependencies
        run: dotnet restore src/Daytona.sln
      - name: Build Solution
        run: dotnet build src/Daytona.sln -- configuration Release --no-restore
      - name: Pack Solution
        run: dotnet pack --no-build src/Daytona/Daytona.csproj -p:PackageVersion=${{github.run_id}}.${{github.run_number}} -c Release -o .
      - name: Push Package
        run: |
          dotnet nuget add source --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push **/*.nupkg --source github
